circumference: 200
full_rollout_only: true
horizon: 1000
n_rollouts_per_step: 1
n_steps: 100
result_save: evaluations/test.csv
save_agent: true
skip_stat_steps: 0
skip_vehicle_info_stat_steps: false
tb: true
vehicle_info_save: trajectories/test.npz
warmup_steps: 0
wb: false
